### ISSUE TITLE
"SCIM Service Provider"

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-events#13]
In the abstract, and throughout the doc the concept of a SCIM Service Provider is used.  This language does not appear in the original [RFC 7642](https://datatracker.ietf.org/doc/rfc7642/).  In 7642 this concept is referred to as a Cloud Service Provider (CSP).  While I recognize CSP is a terrible, overloaded acronym, I am concerned about adding a new term.

How does this align with the work done by @pamelatech and Paulo on use cases and their naming?

**Comment by dhs-aws** [comment]
There are also references to a "SCIM provider".  We should work to normalize the language around the client and server in the draft to be internally consistent and consistent with other RFCs and/or the use cases documentation.

**Comment by dhs-aws** [comment]
Rereading the final paragraph of section 1 you'll see the two terms above as well as the term, "receiver", which I believe maps to the SCIM client that is receiving a SET.

**Comment by independentid** [comment]
No they do not. 7642 terminology has never been aligned with 7643 and 7644In part it is because scim is a profile of http and uses its terms. PhilOn Nov 21, 2023, at 3:07 PM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
In the abstract, and throughout the doc the concept of a SCIM Service Provider is used.  This language does not appear in the original RFC 7642.  In 7642 this concept is referred to as a Cloud Service Provider (CSP).  While I recognize CSP is a terrible, overloaded acronym, I am concerned about adding a new term.
How does this align with the work done by @pamelatech and Paulo on use cases and their naming?

**Comment by independentid** [comment]
I will check the draft. But in no way is a scim client always a “receiver”.  It merely could be. In my demo a couple meetings ago I showed the wg a replication demo where each server was both transmitter and receiver. PhilOn Nov 21, 2023, at 3:12 PM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
Rereading the final paragraph of section 1 you'll see the two terms above as well as the term, "receiver", which I believe maps to the SCIM client that is receiving a SET.

**Comment by dhs-aws** [comment]
Thanks for the clarification.  As I read the draft, I found myself coming back to the idea that it's not specified whether the SCIM client or server can be senders and/or receivers.  

I recommend finding a way to update the text to ensure readers are clear that the roles of client and server, sender and receiver, are not mapped 1:1 in any static configuration.  I can envision a situation where two systems involved in DBR are authoritative for different attributes.  In that case, both could act as SCIM clients and servers.  Equally, they could both act as sender and receiver of SETs.

**Comment by independentid** [comment]
AgreedPhilOn Nov 21, 2023, at 3:27 PM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
Thanks for the clarification.  As I read the draft, I found myself coming back to the idea that it's not specified whether the SCIM client or server can be senders and/or receivers.
I recommend finding a way to update the text to ensure readers are clear that the roles of client and server, sender and receiver, are not mapped 1:1 in any static configuration.  I can envision a situation where two systems involved in DBR are authoritative for different attributes.  In that case, both could act as SCIM clients and servers.  Equally, they could both act as sender and receiver of SETs.

**Comment by dhs-aws** [comment]
I now see where SCIM service provider is used broadly in 7643/7644.  No need for changes on that language.

@independentid , do you want me to close this issue and open a new issue on the server/client sender/receiver language?

**Comment by independentid** [comment]
I would close. Take a look at terminology section in the events draft too. PhilOn Nov 21, 2023, at 3:32 PM, Dean H. Saxe - AWS Identity ***@***.***> wrote:﻿
I now see where SCIM service provider is used broadly in 7643/7644.  No need for changes on that language.
@independentid , do you want me to close this issue and open a new issue on the server/client sender/receiver language?

**Comment by independentid** [comment]
I am doing another review on terminology. Certainly one of the complicating issuers is that Transmitter and Receiver are SET terms which came about because HTTP client and service providers are the opposite meaning between RFC8935 and RFC8936.  

I want to strike a balance and not rehash the reasoning that SET took inside the SCIM spec if possible.
